apiVersion: v1
kind: Service
metadata:
  name: django-api-service
spec:
  selector:
    app: django-api
  type: NodePort       # or LoadBalancer in cloud
  ports:
    - protocol: TCP
      port: 8000       # Cluster port
      targetPort: 8000 # Container port
      nodePort: 30007  # Node port for accessing from localhost
